### ISSUE TITLE
PFI: Automate Closed message

### ISSUE THREAD

**Issue by angiejones** [TBD54566975/workshop-tbdex-abc-wallet#10]

**Comment by kirahsapong** [comment]
Addressed in [this](https://github.com/tbdeng/workshop-tbdex-abc-pfi/commit/75a061847e19e0b7c78e7d9e8a22987d8469ea78) and [this commit](https://github.com/tbdeng/workshop-tbdex-abc-pfi/commit/9ca462784e2ca064d16172778e0c80bb90aa536c) of abc-pfi
