### ISSUE TITLE
PFI: Automate OrderStatus messages

### ISSUE THREAD

**Issue by angiejones** [TBD54566975/workshop-tbdex-abc-wallet#9]

**Comment by kirahsapong** [comment]
Addressed in [this](https://github.com/tbdeng/workshop-tbdex-abc-pfi/commit/4ade233be79e1e3c50f0878d007cca5c630edf27) and [this commit](https://github.com/tbdeng/workshop-tbdex-abc-pfi/commit/75a061847e19e0b7c78e7d9e8a22987d8469ea78) to abc-pfi
